### PR TITLE
Component/wizard modal

### PR DESCRIPTION
**Pull request by tarikhamilton**
https://app.zeplin.io/project/5b4e44c4113211861caaa7c1/screen/5c757703310547bc7e057763

This is the `<WizardModal />`, it contains 3 other internal components (Header, Body, Footer), and also adding `<SmallTitle />`, which we've talked about being like a label of sorts.

Fixed pagination dots having some extra height being inline-block

### CODE REVIEW

**Comment by tarikhamilton** [comment]
> Unable to click "save" at smaller viewport heights (around 550px)

@simonwebdesign What is the expected behavior on small windows or screens?

**Comment by josephfusco** [comment]
@tarikhamilton Check out https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content & click "Launch demo modal"

**Comment by tarikhamilton** [comment]
> @tarikhamilton Check out https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content & click "Launch demo modal"

I know what it could be, but I just wanted to design it to @simonwebdesign 's spec. There are multiple scroll demos on that page: one scrolls the entire modal, the other scrolls just the body.

I've talked to him and he said just shrink the body.

**Comment by josephfusco** [comment]
> There are multiple scroll demos on that page: one scrolls the entire modal, the other scrolls just the body.

Sorry for the confusion; I meant the first one that scrolls the entire body and not just inside the modal.

**Pull request merged**
